version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "06:00"
  open-pull-requests-limit: 10
  assignees:
  - codl
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "06:00"
  open-pull-requests-limit: 10
  assignees:
  - codl
