"""empty message

Revision ID: 711770097f06
Revises: e46c5fd68037
Create Date: 2017-07-31 17:54:11.215759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711770097f06'
down_revision = 'e46c5fd68037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('policy_ignore_favourites', sa.Boolean(), server_default='TRUE', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'policy_ignore_favourites')
    # ### end Alembic commands ###
