"""empty message

Revision ID: 7379bfac4379
Revises: 995890c26959
Create Date: 2017-08-01 23:35:17.924428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7379bfac4379'
down_revision = '995890c26959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('favourite', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'favourite')
    # ### end Alembic commands ###
