"""empty message

Revision ID: 9fab742962ef
Revises: 711770097f06
Create Date: 2017-08-01 00:33:59.183437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fab742962ef'
down_revision = '711770097f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('policy_delete_every', sa.Interval(), server_default='0', nullable=True))
    op.add_column('accounts', sa.Column('policy_keep_latest', sa.Integer(), server_default='0', nullable=True))
    op.add_column('accounts', sa.Column('policy_keep_younger', sa.Interval(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'policy_keep_younger')
    op.drop_column('accounts', 'policy_keep_latest')
    op.drop_column('accounts', 'policy_delete_every')
    # ### end Alembic commands ###
