"""empty message

Revision ID: e036b007017c
Revises: 9fab742962ef
Create Date: 2017-08-01 22:45:28.450097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e036b007017c'
down_revision = '9fab742962ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('last_delete', sa.DateTime(), server_default='epoch', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'last_delete')
    # ### end Alembic commands ###
