"""empty message

Revision ID: e46c5fd68037
Revises: f11fe22d6169
Create Date: 2017-07-31 17:10:09.833883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46c5fd68037'
down_revision = 'f11fe22d6169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('policy_enabled', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'policy_enabled')
    # ### end Alembic commands ###
